[book]
authors = ["Gunpreet Singh"]
language = "en"
multilingual = false
src = "src"
title = "Car-Bon Docs"

[output.html]
site-url = "/Car-Bon-Docs/"

[preprocessor.toc]
marker = "[[_TOC_]]"
max-level = 4